skip tests if gdktarget!=x11, since GUI tests need Xvfb. only start Xvfb
2007-12-07 13:16:33  Tim Janik  <timj@imendio.com>

        * Makefile.decl: skip tests if gdktarget!=x11, since GUI tests need
        Xvfb. only start Xvfb if TEST_PROGS is not empty. moved "set -e" out
        of XVFB_START, since it's the GTESTER invokation that needs this.



svn path=/trunk/; revision=19125

diff --git a/Makefile.decl b/Makefile.decl
--- a/Makefile.decl
+++ b/Makefile.decl
@@ -16,19 +16,22 @@ XIDS = 101 102 103 104 105 106 107 197 199 211 223 227 293 307 308 309 310 311 \
   1008 1009 4703 4721 4723 4729 4733 4751 9973 9974 9975 9976 9977 9978 9979 \
   9980 9981 9982 9983 9984 9985 9986 9987 9988 9989 9990 9991 9992 9993 9994 \
   9995 9996 9997 9998 9999
+SKIP_GDKTARGET = \
+	test "$(gdktarget)" != "x11" \
+	&& echo "Gtk+Tests:INFO: Skipping GUI tests for non-X11 target."
 XVFB_START = \
 	${XVFB} -help 2>/dev/null 1>&2 \
 	&& XID=`for id in $(XIDS) ; do test -e /tmp/.X$$id-lock || { echo $$id; exit 0; }; done; exit 1` \
 	&& { ${XVFB} :$$XID -nolisten tcp -auth /dev/null >/dev/null 2>&1 & \
 	       trap "kill -15 $$! " 0 HUP INT QUIT TRAP USR1 PIPE TERM ; } \
-	|| { echo Failed to start Xvfb environment for testing; exit 1; } \
-	&& set -e ; DISPLAY=:$$XID; export DISPLAY
+	|| { echo "Gtk+Tests:ERROR: Failed to start Xvfb environment for X11 target tests."; exit 1; } \
+	&& DISPLAY=:$$XID && export DISPLAY
 # call as: $(XVFB_START) && someprogram
 
 # test: run all tests in cwd and subdirs
 test:	${TEST_PROGS}
-	@$(XVFB_START) && { \
-	  test -z "${TEST_PROGS}" || ${GTESTER} --verbose ${TEST_PROGS} ; \
+	@$(SKIP_GDKTARGET) || test -z "${TEST_PROGS}" || { \
+	  $(XVFB_START) && { set -e; ${GTESTER} --verbose ${TEST_PROGS}; }; \
 	}
 	@ for subdir in $(SUBDIRS) ; do \
 	    test "$$subdir" = "." -o "$$subdir" = "po" -o "$$subdir" = "po-properties" || \
@@ -47,13 +50,14 @@ test-report perf-report full-report:	${TEST_PROGS}
 	    test "$$subdir" = "." -o "$$subdir" = "po" -o "$$subdir" = "po-properties" || \
 	    ( cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $@ ) || exit $? ; \
 	  done ; \
-	  test -z "${TEST_PROGS}" || { \
+	  $(SKIP_GDKTARGET) || test -z "${TEST_PROGS}" || { \
 	    case $@ in \
 	    test-report) test_options="-k";; \
 	    perf-report) test_options="-k -m=perf";; \
 	    full-report) test_options="-k -m=perf -m=slow";; \
 	    esac ; \
 	    $(XVFB_START) && { \
+	      set -e; \
 	      if test -z "$$GTESTER_LOGDIR" ; then \
 	        ${GTESTER} --verbose $$test_options -o test-report.xml ${TEST_PROGS} ; \
 	      elif test -n "${TEST_PROGS}" ; then \
