configure.in: require GLib 1.1.5

diff --git a/sanity_check b/sanity_check
--- a/sanity_check
+++ b/sanity_check
@@ -40,6 +40,14 @@ else
 	exit 1
 fi
 
+echo -n "configure.in..."
+if [ "x`grep $VERSION gtk+-$VERSION/configure.in | wc -l | awk -F' ' '{print $1}'`" == "x2" ]; then 
+	echo "ok" 
+else
+	echo "failed."
+	exit 1
+fi
+
 
 echo ""
 echo "Number of lines in created documentation files:"
