Incremented version to 1.2.0. -Shawn <amundson@gtk.org>
Incremented version to 1.2.0.  -Shawn <amundson@gtk.org>

Also:

Wed Feb 24 05:26:20 CST 1999 Shawn T. Amundson <amundson@gtk.org>

        * gtk/gtkitemfactory.h: added a dummy gpointer to
          GtkItemFactoryClass for Tim Janik.

Mon Feb 22 21:22:11 1999  Owen Taylor  <otaylor@redhat.com>

        * gtk/gtkcontainer.h gtk/gtkwidget.h: Added some
          padding to class structures to allow addition
          of signals without breaking binary compatibility.

diff --git a/sanity_check b/sanity_check
--- a/sanity_check
+++ b/sanity_check
@@ -13,7 +13,7 @@ echo "Checking gtk+-$VERSION.tar.gz..."
 tar xfz gtk+-$VERSION.tar.gz
 
 
-for file in README gtk+.spec docs/gtk-config.1
+for file in gtk+.spec docs/gtk-config.1
 do
 	echo -n "$file... "
 	if [ "x`grep $VERSION gtk+-$VERSION/$file | wc -l | awk -F' ' '{print $1}'`" == "x1" ]; then
@@ -23,6 +23,14 @@ do
 		exit 1
 	fi
 done
+
+echo -n "README..."
+if [ "x`grep $VERSION gtk+-$VERSION/README | wc -l | awk -F' ' '{print $1}'`" == "x4" ]; then 
+	echo "ok" 
+else
+	echo "failed."
+	exit 1
+fi
 
 echo -n "INSTALL..."
 if [ "x`grep $VERSION gtk+-$VERSION/INSTALL | wc -l | awk -F' ' '{print $1}'`" == "x3" ]; then 
